# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target '2020dong' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 2020dong
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'YYKit'
  pod 'SDWebImage'
  pod 'CocoaAsyncSocket'
  pod 'MJRefresh'
  pod 'MBProgressHUD'
  pod 'TZImagePickerController'  
  pod 'RMMapper'

  target '2020dongTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '2020dongUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
